repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args:
        - --allow-missing-credentials
      - id: detect-private-key
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: chart-testing
        name: chart-testing
        entry: ct lint --config ct.yaml --target-branch main --debug
        language: system
        pass_filenames: false
