apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/replicas: {{ .Values.replicas | quote }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/replicas: {{ .Values.replicas | quote }}
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      serviceAccountName: {{ include "app.name" . }}
      containers:
      - name: {{ include "app.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ include "app.imagePullPolicy" . }}
        env:
        - name: LOG_LEVEL
          value: INFO
        - name: SOURCE_LABEL_PREFIX
          value: {{ .Values.source_label_prefix }}
        - name: DESTINATION_LABEL_PREFIX
          value: {{ .Values.destination_label_prefix }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /tmp
            name: tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
      volumes:
      - name: tmp
        emptyDir: {}
