apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.name" . }}-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update", "watch"]
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.name" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "app.name" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
